### ISSUE TITLE
Repository Add method confusing name

### ISSUE THREAD

**Issue by darkspock** [cqrs-by-example/book-issues#8]
In the example of Repository at the begining of the book:
interface CheepRepository
 {
 public function add(Cheep $cheep): void;

I think is better to call it store or persist, as later in the update example you call add( ), what is confusing.

**Comment by keyvanakbary** [comment]
Repositories represent collections, not databases. The database implementation is a detail that should be hidden behind the interface (that's why it belongs to Infrastructure). This is explained in the [DDD in PHP book](https://leanpub.com/ddd-in-php) in case you are interested. Thanks for your contribution!

**Comment by darkspock** [comment]
I already read the book.
Then call it Add and Set, using always Add is confusing.
